kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-create-user-realm-role-mappings-configmap
  labels:
    app: {{ .Chart.Name }}
data:
  user-realm-role-mappings.json: |
    [
      {
        "name": "Role 1"
      },
      {
        "name": "Another Role 2"
      }
    ]
