kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-client-scope-mappings-configmap
  labels:
    app: {{ .Chart.Name }}
data:
  client-scope-mappings.json: |
    [
        {
            "name": "create-client"
        },
        {
            "name": "impersonation"
        }
    ]