apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-create-ext-client-hook
  labels:
    app: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: keycloak-client
          image: "armdocker.rnd.ericsson.se/proj-orchestration-so/keycloak-client:1.0.0-17"
          env:
          - name: IAM_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.iam.adminSecret | quote }}
                key: {{ .Values.global.iam.userKey | quote }}
          - name: IAM_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.iam.adminSecret | quote }}
                key: {{ .Values.global.iam.passwordKey | quote }}
          - name: IAM_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.clientId | quote }}
                key: clientid
          - name: DEFINED_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.userSecret | quote }}
                key: username
          - name: DEFINED_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.userSecret | quote }}
                key: password
          command:
          - "export CLIENT_SECRET=$(/keycloak_client/entrypoint.sh create ext-client"
          - "--keycloak_hostname={{ .Values.global.hosts.iam }}"
          - "--keycloak_user=$(IAM_ADMIN_USER)"
          - "--keycloak_password '$(IAM_ADMIN_PASSWORD)'"
          - "--client-id $(IAM_CLIENT_ID) && ./entrypoint.sh get client_secret"
          - "--keycloak_hostname={{ .Values.global.hosts.iam }}"
          - "--keycloak_user=$(IAM_ADMIN_USER)"
          - "--keycloak_password='$(IAM_ADMIN_PASSWORD)'"
          - "--client-id $(IAM_CLIENT_ID))"
          - "/keycloak_client/entrypoint.sh create idp"
          - "--keycloak_hostname={{ .Values.global.hosts.iam }}"
          - "--keycloak_user=$(IAM_ADMIN_USER)"
          - "--keycloak_password '$(IAM_ADMIN_PASSWORD)'"
          - "--client-id $(IAM_CLIENT_ID)"
          - "--client-secret $CLIENT_SECRET"
          volumeMounts:
          - name: create-cacert-volume
            mountPath: /mnt/certs
      volumes:
      - name: create-cacert-volume
        secret:
          secretName: {{ .Values.iam.cacert.secretName }}
          items:
            - key: {{ .Values.iam.cacert.key }}
              path: {{ .Values.iam.cacert.filePath }}