apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-create-group-hook
  labels:
    app: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: keycloak-client
          image: "armdocker.rnd.ericsson.se/proj-orchestration-so/keycloak-client:1.0.0-17"
          env:
          - name: IAM_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.iam.adminSecret | quote }}
                key: {{ .Values.global.iam.userKey | quote }}
          - name: IAM_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.iam.adminSecret | quote }}
                key: {{ .Values.global.iam.passwordKey | quote }}
          args:
          - "create"
          - "group"
          - "--keycloak_hostname={{ .Values.global.hosts.iam }}"
          - "--keycloak_user=$(IAM_ADMIN_USER)"
          - "--keycloak_password=$(IAM_ADMIN_PASSWORD)"
          - "--config=/config/group.json"
          volumeMounts:
          - name: create-group-volume
            mountPath: /config
          - name: create-cacert-volume
            mountPath: /mnt/certs
      volumes:
      - name: create-group-volume
        configMap:
          name: {{ .Chart.Name }}-group-configmap
          defaultMode: 0777
      - name: create-cacert-volume
        secret:
          secretName: {{ .Values.iam.cacert.secretName }}
          items:
            - key: {{ .Values.iam.cacert.key }}
              path: {{ .Values.iam.cacert.filePath }}
